% Decompose Signal using the MODWT
% Generated by MATLAB(R) 9.8 and Wavelet Toolbox 5.4.
% Generated on: 30-Nov-2024 19:24:05
% Logical array for selecting reconstruction elements
levelForReconstruction = [false, false, false, false, false, false, true, true, true, true, true, true, true, true, true];
% Perform the decomposition using modwt
wt = modwt(bef_all, 'sym4', 14);
% Construct MRA matrix using modwtmra
mra = modwtmra(wt, 'sym4');
mra = mra(7:end,:);
% Sum along selected multiresolution signals
%bef_all1 = sum(mra(levelForReconstruction,:),1);
