%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\Junior\Google Drive\doktoranti\doktorant-aleksandar-balabanov\Data sets\Data for analysis\!ALL RAW DATA COMBINED.xlsx
%    Worksheet: April 7 2023
%
% Auto-generated by MATLAB on 30-Nov-2024 18:14:30

%% Setup the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 13);

% Specify sheet and range
opts.Sheet = "Jan 2024"; % "April 7 2023", "April 26 2023", "Oct 2023"
opts.DataRange = "A:M";

% Specify column names and types
opts.VariableNames = ["Var1", "HR", "Var3", "Var4", "Var5", "Var6", "Var7", "Var8", "Var9", "Var10", "Var11", "HRConfidence", "HRV"];
opts.SelectedVariableNames = ["HR", "HRConfidence", "HRV"];
opts.VariableTypes = ["char", "double", "char", "char", "char", "char", "char", "char", "char", "char", "char", "double", "double"];

% Specify file level properties
opts.ImportErrorRule = "omitrow";
opts.MissingRule = "omitrow";

% Specify variable properties
opts = setvaropts(opts, ["Var1", "Var3", "Var4", "Var5", "Var6", "Var7", "Var8", "Var9", "Var10", "Var11"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "Var3", "Var4", "Var5", "Var6", "Var7", "Var8", "Var9", "Var10", "Var11"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, ["HR", "HRConfidence", "HRV"], "TreatAsMissing", '');

% Import the data
ALLRAWDATACOMBINED = readtable("!ALL RAW DATA COMBINED.xlsx", opts, "UseExcel", false);
output = ALLRAWDATACOMBINED(ALLRAWDATACOMBINED.HRV<101,:);


if sum(output.HRConfidence<20)>0
    begin = max(find(output.HRConfidence<20))+1;
    output = output(begin:end,:);
end

after2 = output;%before1, before2, after1
%% Clear temporary variables
clear opts ALLRAWDATACOMBINED begin output